// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgEQ-dSwvlXTYiJKCbcpB1msNdisf7zXM',
    appId: '1:372148657456:web:ac7b216447214d69f7fcf5',
    messagingSenderId: '372148657456',
    projectId: 'fir-tutorial-3c5bc',
    authDomain: 'fir-tutorial-3c5bc.firebaseapp.com',
    storageBucket: 'fir-tutorial-3c5bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1YDbu5qEg8wodjG7C6zd9RU0PAl79rM',
    appId: '1:372148657456:android:da94b5105315872ef7fcf5',
    messagingSenderId: '372148657456',
    projectId: 'fir-tutorial-3c5bc',
    storageBucket: 'fir-tutorial-3c5bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3IsoxtFzkRUu2Fn5TXKcegFLQZPrxzPk',
    appId: '1:372148657456:ios:b5f23a6aae5ca35cf7fcf5',
    messagingSenderId: '372148657456',
    projectId: 'fir-tutorial-3c5bc',
    storageBucket: 'fir-tutorial-3c5bc.appspot.com',
    iosClientId:
        '372148657456-imrn9tu1v1bpdqqeeop4s75mo6hgj4oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3IsoxtFzkRUu2Fn5TXKcegFLQZPrxzPk',
    appId: '1:372148657456:ios:b5f23a6aae5ca35cf7fcf5',
    messagingSenderId: '372148657456',
    projectId: 'fir-tutorial-3c5bc',
    storageBucket: 'fir-tutorial-3c5bc.appspot.com',
    iosClientId:
        '372148657456-imrn9tu1v1bpdqqeeop4s75mo6hgj4oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTut',
  );
}
